#github
library(usethis)
library(gitcreds)
gitcreds_set()
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
use_github()
#code
library(dlnm)
library(splines)
